#baseline:
#  name: baseline
#
#firebase-config:
#  name: config
#  dependencies:
#    - com.google.firebase:firebase-config-ktx
#
#firebase-common:
#  name: common
#  dependencies:
#    - com.google.firebase:firebase-common

firebase-crashlytics:
  name: crash
  dependencies:
    - com.google.firebase:firebase-crashlytics-ktx
  plugins:
    - com.google.firebase.crashlytics

#firebase-database:
#  name: database
#  dependencies:
#    - com.google.firebase:firebase-database-ktx
#
#firebase-dynamic-links:
#  name: dynamiclinks
#  dependencies:
#    - com.google.firebase:firebase-dynamic-links-ktx
#
#firebase-firestore:
#  name: firestore
#  dependencies:
#    - com.google.firebase:firebase-firestore-ktx
#
#firebase-functions:
#  name: functions
#  dependencies:
#    - com.google.firebase:firebase-functions-ktx
#
#firebase-inappmessaging-display:
#  name: inappmessaging
#  dependencies:
#    - com.google.firebase:firebase-analytics-ktx@18.0.3
#    - com.google.firebase:firebase-inappmessaging-ktx
#    - com.google.firebase:firebase-inappmessaging-display-ktx
#
#firebase-messaging:
#  name: messaging
#  dependencies:
#    - com.google.firebase:firebase-messaging-ktx
#
#firebase-perf:
#  name: perf
#  dependencies:
#    - com.google.firebase:firebase-perf-ktx
#  plugins:
#    - com.google.firebase.firebase-perf
#
#firebase-storage:
#  name: storage
#  dependencies:
#    - com.google.firebase:firebase-storage-ktx
#


# TODO(yifany): google3 sdks, customizing FTL devices
# auth
# analytics
# combined
#   - crashlytics + analytics
#   - crashlytics + fireperf
#   - auth + firestore
#   - ...
