name: build-src-check

on:
  pull_request:
    paths:
      - 'buildSrc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-src-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: buildSrc Tests
        env:
          FIREBASE_CI: 1
        run: |
          ./gradlew -b buildSrc/build.gradle.kts -PenablePluginTests=true check
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02
        with:
          files: "**/build/test-results/**/*.xml"
          check_name: "buildSrc Test Results"
