name: Check buildSrc

on:
  pull_request:
    paths:
      - 'buildSrc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-src-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: buildSrc Tests
        env:
          FIREBASE_CI: 1
        run: |
          ./gradlew -b buildSrc/build.gradle.kts -PenablePluginTests=true check
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a
        with:
          files: "**/build/test-results/**/*.xml"
          check_name: "buildSrc Test Results"
