name: Changelog

on:
  pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  changelog-check:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ./ci/danger/Gemfile
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 100
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Setup Bundler
      run: ./ci/danger/setup_bundler.sh
    - name: Danger CHANGELOG verifier
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
      run:
        '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger --dangerfile=./ci/danger/Dangerfile || echo "Skipping Danger for External Contributor"'
