name: Run fireci tests

on:
  pull_request:
    paths:
      - 'ci/**'
      - '.github/workflows/fireci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fireci:
    name: "fireci tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
          pip-version: '26.0.1'
      - run: |
          pip install -e "ci/fireci[test]"
      - run: |
          pytest ci/fireci
      - run: |
          mypy --config-file ci/fireci/pyproject.toml ci/fireci/
