name: Firebase Sessions E2E Tests

on:
  schedule:
    - cron: 24 */4 * * *  # every 4 hours at 24 minutes past the hour
  workflow_dispatch:     # allow triggering the workflow manually

concurrency:
  group: ${{ github.workflow }}

env:
  SESSIONS_E2E_GOOGLE_SERVICES: ${{ secrets.SESSIONS_E2E_GOOGLE_SERVICES }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout firebase-sessions
        uses: actions/checkout@v3.5.3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Add google-services.json
        run: |
          echo $SESSIONS_E2E_GOOGLE_SERVICES | base64 -d > google-services.json

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Run sessions end-to-end tests
        env:
          FTL_RESULTS_BUCKET: fireescape
        run: |
          ./gradlew :firebase-sessions:test-app:deviceCheck withErrorProne -PtargetBackend="prod" -PtriggerCrashes
